### ISSUE TITLE
Crash on unloading, but only after much output

### ISSUE THREAD

**Issue by arn-cx** [equinor/dlisio#182] opened 2019-10-31 09:44 UTC
Platform: Windows/Python 3.5 x64, dlisio 0.1.14

I have a very simple script which benchmarks dlispy and dlisio to see how many files go through the libraries and how fast they are, which triggers a crash if enough data is spammed to the terminal. The script is:

```
import dlisio
import dlispy
import os
import os.path
import time


def main(paths):
    benchmark(do_dlisio, paths)
    #benchmark(do_dlispy, paths)


def benchmark(f, paths):
    failed = 0
    count = 0
    start = time.time()

    for path in paths:
        for dirpath, _, filenames in os.walk(path):
            for filename in filenames:
                if not filename.lower().endswith('.dlis'): continue
                print(filename)
                try:
                    count += 1
                    f(os.path.join(dirpath, filename))
                except Exception as e:
                    failed += 1
                    print('{}: {}'.format(filename, e))
                print('.')

    end = time.time()
    print('{}: {}/{} of {} failed'.format(f.__name__, end-start, failed, count))


def do_dlispy(filename):
    dlispy.parse(filename)


def do_dlisio(filename):
    dlisio.load(filename)


if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('paths', nargs='+')
    args = parser.parse_args()
    main(args.paths)
```

Running this on my corpus of DLIS files (498 files, all from Diskos) triggers a Python crash with the error "Fatal Python error: deallocating None". Apparently this can be caused by calling Py_DECREF on the C object backing None.

Locally, several kinds of modifications make the crash go away:
- Returning immediately from `benchmark()` after processing the first file
- Commenting out one (or both) of the prints in the innermost loop

Since the crash happens after the end of the script, I think the most likely culprit is unloading logic in the dlisio native extension or some kind of other end-of-program logic like GC of global state in the library, but I don't have a good explanation for why it only triggers when lots of output is spammed to stdout.

**Comment by ErlendHaa** [comment] 2019-11-01 10:34
Hi, thanks for the detailed report

Indeed this is some wierd behavior and we might have a bug in our code. However I'm not able to reproduce this on my machine. I tried running your script on a different database with ~1000 files with no issues. 

Note that you are opening files and not closing them, relying on GC to do the job (which it should). Out of interest, what happens if you manually close the file, e.g:
```
def do_dlisio(filename):
    f = dlisio.load(filename)
    f.close()
```

**Comment by arn-cx** [comment] 2019-11-01 13:52
Closing the returned object properly also makes the error go away. Given that, one scenario that might fit the observations is that some extension code called by `close()` accidentally decrefs None, which is fine because it gets incremented back up some by surrounding code, but if a huge pile of that code gets called many times in a row it might decref None to zero.

I guess that might fit with the sensitivity to unrelated changes in the code too, if it's dependent on GC order of objects and the end of the program.

**Comment by jokva** [comment] 2019-11-01 14:45
If closing fixes the issue, it narrows down the sources of errors dramatically. We'll get right on it.

**Comment by ErlendHaa** [comment] 2019-12-03 09:36
Unfortunately, we are not able to reproduce the behavior you are describing. 

I will close this issue now, as closing the file solves the problem for you. However there might be a bug here, so feel free to reopen it you have any more information that we can use to reproduce

**Closed by ErlendHaa** 2019-12-03 09:36 UTC
